import fs from "node:fs";
import path from "node:path";
import { eq } from "drizzle-orm";
import { getDb } from "../src/db/index.ts";
import {
  brand,
  shoe,
  type ShoeScenario,
  type SHOE_CLOSURES,
  type SHOE_DOWNTURNS,
  type SHOE_LEVELS,
  type SHOE_STIFFNESS,
  type SHOE_WIDTHS,
} from "../src/db/schema.ts";

type SeedBrand = {
  name: string;
  description: string;
};

type SeedShoe = {
  brand: string;
  model: string;
  price: number;
  scenarios: ShoeScenario[];
  stiffness: (typeof SHOE_STIFFNESS)[number];
  width: (typeof SHOE_WIDTHS)[number];
  level: (typeof SHOE_LEVELS)[number];
  downturn: (typeof SHOE_DOWNTURNS)[number];
  closure: (typeof SHOE_CLOSURES)[number];
  material: string;
  images?: string[];
};

const BRANDS: SeedBrand[] = [
  { name: "La Sportiva", description: "意大利顶级品牌，竞技与高性能攀岩鞋的代名词。" },
  { name: "Scarpa", description: "意大利老牌，性能与舒适兼备，产品线覆盖全场景。" },
  { name: "Tenaya", description: "西班牙品牌，以舒适包裹与精准脚感著称。" },
  { name: "Evolv", description: "美国品牌，抱石与馆内场景的热门选择。" },
  { name: "Unparallel", description: "韩国品牌，橡胶性能出色，性价比高。" },
  { name: "Boreal", description: "西班牙品牌，攀岩橡胶技术的先行者。" },
  { name: "Mad Rock", description: "美国品牌，高性价比，新手友好。" },
  { name: "Butora", description: "韩国品牌，以合脚舒适与扎实做工闻名。" },
  {
    name: "Five Ten",
    description: "美国品牌（现属 adidas），传奇 Stealth 橡胶的发明者，抱石鞋经典。",
  },
  { name: "Ocún", description: "捷克品牌，传承 Rock Pillars 制鞋工艺，性能与舒适兼备。" },
  {
    name: "Red Chili",
    description: "德国品牌，由自由攀岩先驱 Stefan Glowacz 创立，高性能产品线丰富。",
  },
  { name: "So Ill", description: "加拿大品牌，设计语言大胆，抱石场景的新锐力量。" },
  { name: "AKU", description: "意大利品牌，蒙特贝卢纳手工制造，高端攀岩鞋黑马。" },
  {
    name: "ARTDENNX",
    description: "国产攀岩鞋品牌，主打高性价比入门与进阶鞋款，岩时攀岩独家发售。",
  },
  {
    name: "Hylonomus",
    description: "国产专业攀岩鞋品牌「始林蜥」，以最早爬行动物 Hylonomus 命名，新锐力量。",
  },
];

const SHOES: SeedShoe[] = [
  {
    brand: "La Sportiva",
    model: "Solution",
    price: 1380,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "Miura 系带版",
    price: 1180,
    scenarios: ["难度", "馆内全能"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "适度",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Katana",
    price: 1080,
    scenarios: ["馆内全能", "难度"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Tarantulace",
    price: 680,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Finale",
    price: 850,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "套脚",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Mythos",
    price: 980,
    scenarios: ["传统多段", "馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Skwama",
    price: 1280,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "Futura",
    price: 1350,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "Genius",
    price: 1220,
    scenarios: ["抱石", "难度"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "TC Pro",
    price: 1320,
    scenarios: ["传统多段", "难度"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "La Sportiva",
    model: "Otaki",
    price: 1150,
    scenarios: ["难度", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "Cobra 4:9",
    price: 1250,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "套脚",
    material: "合成纤维",
  },

  {
    brand: "Scarpa",
    model: "Instinct VS",
    price: 1280,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Scarpa",
    model: "Booster",
    price: 1250,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Scarpa",
    model: "Drago",
    price: 1320,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Scarpa",
    model: "Drago LV",
    price: 1320,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Scarpa",
    model: "Origin",
    price: 780,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Scarpa",
    model: "Helix",
    price: 950,
    scenarios: ["馆内全能", "难度"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "Tenaya",
    model: "Masai",
    price: 1150,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Tenaya",
    model: "Mundaka",
    price: 1180,
    scenarios: ["抱石", "竞技"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Tenaya",
    model: "Tanta",
    price: 880,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Tenaya",
    model: "Oasi",
    price: 1150,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Tenaya",
    model: "Tarifa",
    price: 1120,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Tenaya",
    model: "Ra",
    price: 950,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Tenaya",
    model: "Inti",
    price: 820,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Evolv",
    model: "Phantom",
    price: 1350,
    scenarios: ["抱石"],
    stiffness: "硬",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-phantom.jpg"],
  },
  {
    brand: "Evolv",
    model: "Phantom LV",
    price: 1350,
    scenarios: ["抱石"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-phantom-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Phantom Pro",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "硬",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-phantom-pro.jpg"],
  },
  {
    brand: "Evolv",
    model: "Phantom Pro LV",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-phantom-pro-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman",
    price: 1200,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman LV",
    price: 1200,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "窄",
    level: "极致性能",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Lace",
    price: 790,
    scenarios: ["难度", "抱石"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-lace.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Lace LV",
    price: 790,
    scenarios: ["难度", "抱石"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-lace-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Pro",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "硬",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-pro.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Pro LV",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-pro-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Trance",
    price: 1350,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-trance.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman Trance LV",
    price: 1350,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-trance-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman 2S",
    price: 1200,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-2s.jpg"],
  },
  {
    brand: "Evolv",
    model: "Shaman 2S LV",
    price: 1200,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "窄",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-shaman-2s-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Geshido",
    price: 1200,
    scenarios: ["馆内全能", "难度"],
    stiffness: "硬",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-geshido.jpg"],
  },
  {
    brand: "Evolv",
    model: "Geshido LV",
    price: 1200,
    scenarios: ["馆内全能", "难度"],
    stiffness: "硬",
    width: "窄",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-geshido-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Geshido Lace",
    price: 720,
    scenarios: ["馆内全能", "难度"],
    stiffness: "硬",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "系带",
    material: "皮革",
    images: ["/shoe-images/evolv-geshido-lace.jpg"],
  },
  {
    brand: "Evolv",
    model: "V6",
    price: 1160,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-v6.jpg"],
  },
  {
    brand: "Evolv",
    model: "V6 LV",
    price: 1160,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "窄",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-v6-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Zenist",
    price: 1200,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-zenist.jpg"],
  },
  {
    brand: "Evolv",
    model: "Zenist LV",
    price: 1200,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "软",
    width: "窄",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-zenist-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Zenist Pro",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-zenist-pro.jpg"],
  },
  {
    brand: "Evolv",
    model: "Zenist Pro LV",
    price: 1350,
    scenarios: ["竞技", "抱石"],
    stiffness: "中",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-zenist-pro-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Defy",
    price: 830,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-defy.jpg"],
  },
  {
    brand: "Evolv",
    model: "Defy LV",
    price: 830,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "窄",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-defy-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Defy Lace",
    price: 900,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-defy-lace.jpg"],
  },
  {
    brand: "Evolv",
    model: "Defy Lace LV",
    price: 900,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "窄",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-defy-lace-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Yosemite Bum",
    price: 1390,
    scenarios: ["传统多段", "难度"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-yosemite-bum.jpg"],
  },
  {
    brand: "Evolv",
    model: "Yosemite Bum LV",
    price: 1390,
    scenarios: ["传统多段", "难度"],
    stiffness: "中",
    width: "窄",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: ["/shoe-images/evolv-yosemite-bum-lv.jpg"],
  },
  {
    brand: "Evolv",
    model: "Rave",
    price: 900,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "套脚",
    material: "皮革",
    images: ["/shoe-images/evolv-rave.jpg"],
  },
  {
    brand: "Evolv",
    model: "Kira",
    price: 980,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-kira.jpg"],
  },
  {
    brand: "Evolv",
    model: "Kronos",
    price: 980,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-kronos.jpg"],
  },
  {
    brand: "Evolv",
    model: "Elektra",
    price: 450,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: ["/shoe-images/evolv-elektra.jpg"],
  },
  {
    brand: "Evolv",
    model: "Elektra Lace",
    price: 500,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
    images: ["/shoe-images/evolv-elektra-lace.jpg"],
  },
  {
    brand: "Evolv",
    model: "Venga Youth",
    price: 450,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "套脚",
    material: "合成纤维",
    images: ["/shoe-images/evolv-venga-youth.jpg"],
  },

  {
    brand: "Boreal",
    model: "Ninja",
    price: 1050,
    scenarios: ["竞技", "难度"],
    stiffness: "硬",
    width: "窄",
    level: "极致性能",
    downturn: "适度",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "Boreal",
    model: "Mutant",
    price: 1020,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Boreal",
    model: "Alpha",
    price: 900,
    scenarios: ["难度", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "系带",
    material: "合成纤维",
  },
  {
    brand: "Boreal",
    model: "Joker",
    price: 760,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "皮革",
  },
  {
    brand: "Mad Rock",
    model: "Drifter",
    price: 550,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "Mad Rock",
    model: "Drone CS",
    price: 920,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Mad Rock",
    model: "Haywire",
    price: 800,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Mad Rock",
    model: "Remora",
    price: 700,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },


  {
    brand: "Five Ten",
    model: "Hiangle",
    price: 1280,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },



  {
    brand: "Ocún",
    model: "Ozone Plus",
    price: 1080,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Ocún",
    model: "Jett QC",
    price: 720,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Ocún",
    model: "Rebel",
    price: 880,
    scenarios: ["传统多段", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
  },
  {
    brand: "Red Chili",
    model: "Circuit",
    price: 820,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "Red Chili",
    model: "Fusion",
    price: 980,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "Red Chili",
    model: "Ventic",
    price: 1150,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "So Ill",
    model: "Makoto",
    price: 1200,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "So Ill",
    model: "Street Sender",
    price: 1050,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "AKU",
    model: "Rock Pilot",
    price: 1180,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
  },
  {
    brand: "AKU",
    model: "Zenit",
    price: 950,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
  },
  {
    brand: "La Sportiva",
    model: "Solution Comp",
    price: 1150,
    scenarios: ["抱石", "难度"],
    stiffness: "中",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-solution-comp.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Adam Ondra Comp",
    price: 1300,
    scenarios: ["抱石", "竞技"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-adam-ondra-comp.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Skwama Lite",
    price: 850,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-skwama-lite.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Tarantula",
    price: 560,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "皮革",
    images: [
      "/shoe-images/la-sportiva-tarantula.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Kubo",
    price: 850,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-kubo.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Theory",
    price: 1150,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-theory.jpg",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Mandala",
    price: 1200,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-mandala.png",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Mantra",
    price: 950,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/la-sportiva-mantra.png",
    ],
  },
  {
    brand: "La Sportiva",
    model: "Cobra",
    price: 800,
    scenarios: ["竞技", "抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "适度",
    closure: "套脚",
    material: "皮革",
    images: [
      "/shoe-images/la-sportiva-cobra.jpg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Drago XT",
    price: 1200,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
    images: [
      "/shoe-images/scarpa-drago-xt.png",
    ],
  },
  {
    brand: "Scarpa",
    model: "Instinct VSR",
    price: 1150,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/scarpa-instinct-vsr.jpg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Instinct VSR-LV",
    price: 1200,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "窄",
    level: "极致性能",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/scarpa-instinct-vsr-lv.jpg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Furia S",
    price: 780,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "套脚",
    material: "合成纤维",
    images: [
      "/shoe-images/scarpa-furia-s.jpg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Furia Air",
    price: 980,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "套脚",
    material: "合成纤维",
    images: [
      "/shoe-images/scarpa-furia-air.jpg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Reflex VS",
    price: 530,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "宽",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/scarpa-reflex-vs.jpeg",
    ],
  },
  {
    brand: "Scarpa",
    model: "Quantix SF",
    price: 666,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "皮革",
    images: [
      "/shoe-images/scarpa-quantix-sf.jpg",
    ],
  },
  {
    brand: "ARTDENNX",
    model: "Cx rave",
    price: 278,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/artdennx-cx-rave.jpg",
    ],
  },
  {
    brand: "ARTDENNX",
    model: "Cx rave-x",
    price: 268,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/artdennx-cx-rave-x.jpg",
    ],
  },
  {
    brand: "ARTDENNX",
    model: "Cx Red point",
    price: 299,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/cx-red-point.jpg",
    ],
  },
  {
    brand: "Hylonomus",
    model: "V3 悟 GAIN",
    price: 706,
    scenarios: ["馆内全能", "抱石"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/hylonomus-悟.jpg",
    ],
  },
  {
    brand: "Hylonomus",
    model: "V8 砺 WHETSTONE",
    price: 890,
    scenarios: ["难度", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/hylonomus-砺.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Spider",
    price: 899,
    scenarios: ["抱石"],
    stiffness: "中",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
    images: [
      "/shoe-images/butora-spider.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Ibex",
    price: 1199,
    scenarios: ["抱石", "难度"],
    stiffness: "软",
    width: "中",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
    images: [
      "/shoe-images/butora-ibex.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "New Acro",
    price: 999,
    scenarios: ["抱石"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "魔术贴",
    material: "超细纤维",
    images: [
      "/shoe-images/butora-new-acro.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Acro Comp",
    price: 999,
    scenarios: ["抱石", "竞技"],
    stiffness: "软",
    width: "窄",
    level: "极致性能",
    downturn: "激进",
    closure: "系带",
    material: "超细纤维",
    images: [
      "/shoe-images/butora-acro-comp.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Gomi",
    price: 899,
    scenarios: ["抱石", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "适度",
    closure: "魔术贴",
    material: "超细纤维",
    images: [
      "/shoe-images/butora-gomi.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Komet",
    price: 599,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-komet.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Komet Lace",
    price: 599,
    scenarios: ["馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-komet-lace.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Nix",
    price: 759,
    scenarios: ["竞技", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "套脚",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-nix.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Altura",
    price: 935,
    scenarios: ["传统多段", "馆内全能"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "皮革",
    images: [
      "/shoe-images/butora-altura.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Mantra",
    price: 835,
    scenarios: ["馆内全能", "传统多段"],
    stiffness: "中",
    width: "中",
    level: "进阶",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-mantra.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "Libra",
    price: 659,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "系带",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-libra.jpg",
    ],
  },

  {
    brand: "Butora",
    model: "Senegi",
    price: 369,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-senegi.jpg",
    ],
  },
  {
    brand: "Butora",
    model: "New Comet",
    price: 540,
    scenarios: ["馆内全能"],
    stiffness: "软",
    width: "中",
    level: "入门",
    downturn: "自然",
    closure: "魔术贴",
    material: "合成纤维",
    images: [
      "/shoe-images/butora-new-comet.jpg",
    ],
  },
];

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const LOCAL_IMAGE_DIR = path.join(process.cwd(), "public", "shoe-images");
const BRAND_IMAGE_ALIAS: Record<string, string> = {
  Ocún: "ocun",
};
const LAST_RESORT_IMAGE: Record<string, string> = {
  "Hylonomus\u0000V3 悟 GAIN": "hylonomus-悟.jpg",
  "Hylonomus\u0000V8 砺 WHETSTONE": "hylonomus-砺.jpg",
};

let localImageIndex: Map<string, string> | null = null;
function localImageFileName(shoeSeed: SeedShoe): string | undefined {
  if (!fs.existsSync(LOCAL_IMAGE_DIR)) return undefined;
  if (!localImageIndex) {
    localImageIndex = new Map<string, string>();
    for (const file of fs.readdirSync(LOCAL_IMAGE_DIR)) {
      const base = file.replace(/\.(jpe?g|png)$/i, "");
      localImageIndex.set(base.toLowerCase(), file);
      localImageIndex.set(
        base.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-"),
        file,
      );
    }
  }
  const normalize = (value: string) =>
    value
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-")
      .replace(/^-+|-+$/g, "");
  const brandNorm = normalize(
    BRAND_IMAGE_ALIAS[shoeSeed.brand] ?? shoeSeed.brand,
  );
  const modelNorm = normalize(shoeSeed.model);
  const candidates = [
    `${brandNorm}-${modelNorm}`,
    `${modelNorm}`,
    LAST_RESORT_IMAGE[`${shoeSeed.brand}\u0000${shoeSeed.model}`]?.replace(
      /\.(jpe?g|png)$/i,
      "",
    ),
  ];
  for (const candidate of candidates) {
    if (!candidate) continue;
    const file = localImageIndex.get(candidate);
    if (file) return `/shoe-images/${file}`;
  }
  return undefined;
}

function brandHue(name: string): number {
  let hash = 0;
  for (const char of name) hash = (hash * 31 + char.codePointAt(0)!) % 360;
  return hash;
}

function writeSeedImage(shoe: SeedShoe): string {
  const slug = [shoe.brand, shoe.model].map(slugify).filter(Boolean).join("-");
  const publicPath = `/seed/${slug}.svg`;
  const filePath = path.join(process.cwd(), "public", publicPath.slice(1));
  const hue = brandHue(shoe.brand);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600" viewBox="0 0 800 600">
  <rect width="800" height="600" fill="hsl(${hue}, 45%, 30%)"/>
  <rect x="24" y="24" width="752" height="552" fill="none" stroke="hsl(${hue}, 40%, 55%)" stroke-width="2" rx="12"/>
  <text x="400" y="280" font-family="sans-serif" font-size="44" fill="#ffffff" text-anchor="middle">${shoe.brand}</text>
  <text x="400" y="345" font-family="sans-serif" font-size="34" fill="hsl(${hue}, 30%, 85%)" text-anchor="middle">${shoe.model}</text>
</svg>
`;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, svg);
  return publicPath;
}

const db = getDb();

const brandIds = new Map<string, number>(
  db.select().from(brand).all().map((row) => [row.name, row.id]),
);
for (const seedBrand of BRANDS) {
  if (brandIds.has(seedBrand.name)) continue;
  const row = db.insert(brand).values(seedBrand).returning().get();
  brandIds.set(seedBrand.name, row.id);
}

const existingShoeIds = new Map<string, number>(
  db
    .select({ id: shoe.id, brandName: brand.name, model: shoe.model })
    .from(shoe)
    .innerJoin(brand, eq(shoe.brandId, brand.id))
    .all()
    .map((row) => [`${row.brandName}\u0000${row.model}`, row.id]),
);

let inserted = 0;
let updated = 0;
for (const seedShoe of SHOES) {
  const brandId = brandIds.get(seedShoe.brand);
  if (!brandId) throw new Error(`未知品牌: ${seedShoe.brand}`);
  const key = `${seedShoe.brand}\u0000${seedShoe.model}`;
  const values = {
    brandId,
    model: seedShoe.model,
    price: seedShoe.price,
    scenarios: seedShoe.scenarios,
    stiffness: seedShoe.stiffness,
    width: seedShoe.width,
    level: seedShoe.level,
    downturn: seedShoe.downturn,
    closure: seedShoe.closure,
    material: seedShoe.material,
    images:
      seedShoe.images ??
      (function () {
        const local = localImageFileName(seedShoe);
        return local ? [local] : [writeSeedImage(seedShoe)];
      })(),
    status: "approved" as const,
  };
  if (existingShoeIds.has(key)) {
    db.update(shoe).set(values).where(eq(shoe.id, existingShoeIds.get(key)!)).run();
    updated += 1;
    continue;
  }
  db.insert(shoe).values(values).run();
  inserted += 1;
}

console.log(
  `seeded: ${BRANDS.length} brands, ${SHOES.length} shoes (新增 ${inserted}，更新 ${updated} 鞋款)`,
);
